# Generated by Django 2.1.5 on 2019-01-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipment',
            old_name='status',
            new_name='availability',
        ),
    ]
