# Generated by Django 2.1.5 on 2019-04-03 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0002_unacceptedclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scanning_app.TypeOfEquipment'),
        ),
    ]
