# Generated by Django 2.1.5 on 2019-04-07 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0002_unacceptedclient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=128)),
                ('zip_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{2}-\\d{3}$', "Zip code doesn't comply")])),
                ('city', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^(\\(d{3}-\\d{3}-\\d{2}-\\d{2})|(d{3}-\\d{2}-\\d{2}-\\d{3})$', "Nip doesn't comply")])),
                ('regon', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', "Regon doesn't comply")])),
            ],
        ),
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scanning_app.Address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='business_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scanning_app.BusinessInfo'),
        ),
        migrations.AlterField(
            model_name='unacceptedclient',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scanning_app.Address'),
        ),
        migrations.AlterField(
            model_name='unacceptedclient',
            name='business_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='scanning_app.BusinessInfo'),
        ),
    ]
