# Generated by Django 2.1.5 on 2019-03-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0002_auto_20190223_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='availability',
        ),
        migrations.AddField(
            model_name='equipment',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
