# Generated by Django 2.1.5 on 2019-04-05 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0003_auto_20190403_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.TypeOfEquipment'),
        ),
    ]
