# Generated by Django 2.1.5 on 2019-04-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0004_auto_20190405_1109'),
        ('scanning_app', '0003_auto_20190407_0944'),
    ]

    operations = [
    ]
