# Generated by Django 2.1.5 on 2019-04-10 14:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0005_merge_20190408_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.Address'),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='business_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.BusinessInfo'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='nip',
            field=models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^((\\d{3}[-]\\d{3}[-]\\d{2}[-]\\d{2})|(\\d{3}[-]\\d{2}[-]\\d{2}[-]\\d{3}))$', "Nip doesn't comply")]),
        ),
        migrations.AlterField(
            model_name='unacceptedclient',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.Address'),
        ),
        migrations.AlterField(
            model_name='unacceptedclient',
            name='business_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.BusinessInfo'),
        ),
    ]
