# Generated by Django 2.1.5 on 2019-04-17 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0007_auto_20190410_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalinfo',
            name='client_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentalinfo',
            name='equipment_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scanning_app.Equipment'),
        ),
    ]
