# Generated by Django 2.1.5 on 2019-04-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0008_auto_20190417_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeofequipment',
            name='type_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
