# Generated by Django 2.1.5 on 2019-04-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0009_auto_20190417_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
