# Generated by Django 2.1.5 on 2019-04-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0010_auto_20190417_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='name',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
    ]
