# Generated by Django 2.1.5 on 2019-04-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0011_businessinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='max_rent_time',
            field=models.IntegerField(),
        ),
    ]
