# Generated by Django 2.1.5 on 2019-04-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0013_auto_20190420_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='photo_url',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
