# Generated by Django 5.0.7 on 2024-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanning_app', '0014_equipment_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
